/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingUaRouteImport } from './routes/_marketing/ua'
import { Route as MarketingEnRouteImport } from './routes/_marketing/en'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingUaRoute = MarketingUaRouteImport.update({
  id: '/ua',
  path: '/ua',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingEnRoute = MarketingEnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/en': typeof MarketingEnRoute
  '/ua': typeof MarketingUaRoute
}
export interface FileRoutesByTo {
  '/en': typeof MarketingEnRoute
  '/ua': typeof MarketingUaRoute
  '/': typeof MarketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_marketing/en': typeof MarketingEnRoute
  '/_marketing/ua': typeof MarketingUaRoute
  '/_marketing/': typeof MarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/en' | '/ua'
  fileRoutesByTo: FileRoutesByTo
  to: '/en' | '/ua' | '/'
  id:
    | '__root__'
    | '/_marketing'
    | '/_marketing/en'
    | '/_marketing/ua'
    | '/_marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/ua': {
      id: '/_marketing/ua'
      path: '/ua'
      fullPath: '/ua'
      preLoaderRoute: typeof MarketingUaRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/en': {
      id: '/_marketing/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof MarketingEnRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingEnRoute: typeof MarketingEnRoute
  MarketingUaRoute: typeof MarketingUaRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingEnRoute: MarketingEnRoute,
  MarketingUaRoute: MarketingUaRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
